const $ = id => document.getElementById(id)

export const replayButton = $('replay')
export const deathFilter = $('deaths')
export const stayHomeFilter = $('stay-home')
export const graphElement = $('graph')
export const replayElement = $('replay')
export const appUsersElement = $('app_users')
export const totalPeopleElement = $('total_people')
export const infectedPeopleElement = $('infected_people')
export const maxMovementSpeedElement = $('max_movement_speed')
export const deathElement = $('deaths')
export const stayHomeElement = $('stay-home')
